# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: DotNetCoreCLI@2
  displayName: Build Common Library
  inputs:
    command: 'build'
    projects: '.\src\NetworkMonitor.CommonLibrary\NetworkMonitor.CommonLibrary.csproj'
- task: DotNetCoreCLI@2
  displayName: Build Client Library
  inputs:
    command: 'build'
    projects: '.\src\NetworkMonitor.ClientLibrary\NetworkMonitor.ClientLibrary.csproj'
- task: DotNetCoreCLI@2
  displayName: Build Cloud Library
  inputs:
    command: 'build'
    projects: '.\src\NetworkMonitor.CloudLibrary\NetworkMonitor.CloudLibrary.csproj'
