# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: DotNetCoreCLI@2
  displayName: Build Common Library
  inputs:
    projects: 'src/NetworkMonitor.CommonLibrary/NetworkMonitor.CommonLibrary.csproj'
    arguments: '--configuration $(BuildConfiguration)'
- task: DotNetCoreCLI@2
  displayName: Build Client Library
  inputs:
    projects: 'src/NetworkMonitor.ClientLibrary/NetworkMonitor.ClientLibrary.csproj'
    arguments: '--configuration $(BuildConfiguration)'
- task: DotNetCoreCLI@2
  displayName: Build Cloud Library
  inputs:
    projects: 'src/NetworkMonitor.CloudLibrary/NetworkMonitor.CloudLibrary.csproj'
    arguments: '--configuration $(BuildConfiguration)'
- task: DotNetCoreCLI@2
  displayName: Build Windows Service
  inputs:
    projects: 'src/NetworkMonitor.WindowsService/NetworkMonitor.WindowsService.csproj'
    arguments: '--configuration $(BuildConfiguration)'
